#!/usr/bin/env bash

# before running this, make sure you have the output from yass in
# root/yass and the sample models in root/sessions

echo 'Copying notebooks/ to tmp/'
mkdir tmp
cp notebooks/* tmp/

# strip notebooks
echo 'Stripping notebooks...'
./strip_nb tmp/1-intro.ipynb
./strip_nb tmp/2-data-loading.ipynb
./strip_nb tmp/3-model-fit-and-experiments.ipynb
./strip_nb tmp/4-1-model-criticism-GMM.ipynb
./strip_nb tmp/4-2-model-criticism-DPMM.ipynb
./strip_nb tmp/5-clustering-visualization.ipynb
./strip_nb tmp/6-conclusions.ipynb

# convert notebooks to md
echo 'Converting notebooks to markdown...'
jupyter-nbconvert --to markdown tmp/1-intro.ipynb
jupyter-nbconvert --to markdown tmp/2-data-loading.ipynb
jupyter-nbconvert --to markdown tmp/3-model-fit-and-experiments.ipynb
jupyter-nbconvert --to markdown tmp/4-1-model-criticism-GMM.ipynb
jupyter-nbconvert --to markdown tmp/4-2-model-criticism-DPMM.ipynb
jupyter-nbconvert --to markdown tmp/5-clustering-visualization.ipynb
jupyter-nbconvert --to markdown tmp/6-conclusions.ipynb


# count words
echo 'Word count:'
wc -w tmp/1-intro.md tmp/2-data-loading.md tmp/3-model-fit-and-experiments.md tmp/4-1-model-criticism-GMM.md tmp/4-2-model-criticism-DPMM.md tmp/5-clustering-visualization.md tmp/6-conclusions.md

echo 'Removing tmp/'
rm -rf tmp/
