#!/usr/bin/env bash

# create and activate conda env
conda create --name test-project python=3.6.1 -y
source activate test-project

# install pkg and reqs
pip install .
pip install -r requirements.txt

# check flake 8
pytest --flake8

# count length
./count

# generate yass output
run_yass yass_config/demo.yaml config.yaml

# check notebooks run without trouble
mkdir tmp
jupyter nbconvert --execute --output-dir=tmp/ notebooks/2-data-loading.ipynb
jupyter nbconvert --execute --output-dir=tmp/ notebooks/3-model-fit-and-experiments.ipynb
jupyter nbconvert --execute --output-dir=tmp/ notebooks/4-1-model-criticism-GMM.ipynb
jupyter nbconvert --execute --output-dir=tmp/ notebooks/4-2-model-criticism-DPMM.ipynb
jupyter nbconvert --execute --output-dir=tmp/ notebooks/5-clustering-visualization.ipynb
rm -rf tmp

# deactivate and remove end
source deactivate
conda env remove --name test-project -y